type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "Outstanding Graduate Student - Representative of Faculty"
subtitle = "Southern University of Science and Technology"
date = "2023"
content = "Total 13 in SUSTech"

[[items]]
title = "Outstanding Graduate Student"
subtitle = "Southern University of Science and Technology"
date = "2024"
content = ""

[[items]]
title = "Talent Park - Student Talent Under Training"
subtitle = "Shenzhen Institutes of Advanced Technology"
date = "2024"
content = "Total 20 in SIAT"

[[items]]
title = "Outstanding Master's Graduate"
subtitle = "Southern University of Science and Technology"
date = "2025"
content = ""

[[items]]
title = "Outstanding Master's Dissertation"
subtitle = "Southern University of Science and Technology"
date = "2025"
content = "Total 44 in SUSTech"

[[items]]
title = "Dean's Scholarship - Excellence Award"
subtitle = "Shenzhen Institutes of Advanced Technology"
date = "2022"
content = "Top 5% in SIAT"

[[items]]
title = "National Scholarship for Master Student"
subtitle = "Ministry of Education of China"
date = "2023"
content = "0.2% in China, the Highest Student Honor"

[[items]]
title = "Director's Innovation Scholarship - Outstanding Graduate Student"
subtitle = "Shenzhen Institutes of Advanced Technology"
date = "2023"
content = "Top 5% in Department"

[[items]]
title = "Outstanding Graduate Student Scholarship - Second Prize"
subtitle = "Shenzhen Institutes of Advanced Technology"
date = "2024"
content = "Top 3% in SIAT"


