type = "card"
title = "Curriculum Vitae"
# source = "cv.md"

[[items]]
title = "🎓 Educational Background"
subtitle = ""
date = ""
content = """
**[University of Manchester (UoM)](https://www.manchester.ac.uk/)**  
*Sep. 2026 – Present*  
PhD in **Electrical and Electronic Engineering** – Manchester, UK  
- **Research focus:** Dynamic 3D Visual Guidance for Physical Human-Robot Interaction  
- **Supervisors:** [Dr. Zhenhong Li](https://scholar.google.com/citations?user=TxurO5wAAAAJ), [Prof. Andrew Weightman](https://scholar.google.com/citations?user=ntgRzlYAAAAJ), [Prof. Monty Silverdale](https://scholar.google.com/citations?user=Bp9ldq0AAAAJ)

**[Southern University of Science and Technology (SUSTech)](https://www.sustech.edu.cn/en/)**  
*Sep. 2022 – Jun. 2025*  
MEng in **Electronic Science and Technology** – Shenzhen, China  
- Jointly trained at [Shenzhen Institutes of Advanced Technology (SIAT), Chinese Academy of Sciences](https://english.siat.ac.cn/)  
- **Dissertation:** *Research on Structured Light 3D Perception Method for Robot Intelligent Manufacturing*  
- **Supervisor:** [Prof. Zhan Song](https://people.ucas.edu.cn/~zsong?language=en)

**[Southeast University (SEU)](https://www.seu.edu.cn/english/)**  
*Sep. 2017 – Jun. 2021*  
BEng in **Energy and Power Engineering** – Nanjing, China

"""

[[items]]
title = "🏅 Honors & Awards"
subtitle = ""
date = ""
content = """
**Honors**  
- **Outstanding Graduate Student of SUSTech – Representative of Faculty** (13/SUSTech) – *2023*  
- Outstanding Graduate Student of SUSTech – *2024*  
- SIAT Talent Park – Student Talent Under Training (20/SIAT) – *2024*  
- **Outstanding Master's Graduate of SUSTech** – *2025*  
- **Outstanding Master's Dissertation of SUSTech** (44/SUSTech) – *2025*

**Awards**  
- SIAT Dean's Scholarship – Excellence Award (5% in SIAT) – *2022*  
- **National Scholarship for Master Students** (1% in China, highest student honor) – *2023*  
- Director's Innovation Scholarship – Outstanding Graduate Student (5% in Department) – *2023*  
- SIAT Outstanding Graduate Student Scholarship – Second Prize (3% in SIAT) – *2024*

"""

[[items]]
title = "⚙️ Skills"
subtitle = ""
date = ""
content = """
- **Programming:** C++ (primary), Python (PyTorch), MATLAB, LaTeX.  
- **Software:**  
  - SolidWorks (system modelling & 3D printing design)  
  - MeshLab & Geomagic Wrap (point cloud processing & measurement analysis)  
  - Qt (software interface design)  
- **Engineering Capability:**  
  - SL 3D Camera Establishment  
  - Robotic Hand‑Eye System  
  - 3D Point Cloud Processing (registration, segmentation, etc.)  
  - 2D Image Processing (OpenCV, U‑Net, YOLO, etc.)  
- **Languages:** Chinese (native), English (IELTS 7.0).  
"""


