[[news]]
date = "2026-09"
content = "Starting my Ph.D. in Electrical and Electronic Engineering at the University of Manchester"

[[news]]
date = "2025-07"
content = "Graduated from Southern University of Science and Technology, and received the titles of ‘Outstanding Master’s Graduate’ and ‘Outstanding Master’s Thesis’."

[[news]]
date = "2023-11"
content = "Received the National Scholarship for Master Students."
